---
title: "Sobre"
---


Olá! Meu nome é Victor Dogo, atualmente estudante rumo ao título de Bacharel em Estatística pela UFSCar - Universidade Federal de São Carlos. Sou especialmente interessado em programação estatística usando R (foco de boa parte do que eu for postar aqui), mas aberto a muitas outras aplicações (atualmente, procurando aprender Julia).

Neste site, procurarei manter informações relativas aos projetos em que eu esteja participando, posts interessantes que eu venha a escrever ou outras coisas igualmente interessantes mas que eventualmente não sejam relacionadas à Estatística ou Ciência de Dados.

# `r fontawesome::fa(name="graduation-cap")` Formação Acadêmica

### Bacharelado em Estatística - UFSCar: Universidade Federal de São Carlos

* 2017 - Atualmente;
* Ênfase em Estatísticas Sociais.

# `r fontawesome::fa(name="university")` Experiência Universitária

### SEst - Semana da Estatística UFSCar/USP (Membro da Comissão Organizadora)

* 2018 - 2021;
* Atuei como Membro da Diretoria de Marketing (2018), Diretor de Marketing (2019), Membro da Diretoria de Cronograma (2020) e Vice-Presidente (2021).

### EJE - Empresa Júnior de Estatística (Membro da Equipe de Operações)

* 2017 - 2018;
* Fui membro das Diretorias de Comunicação (10/2017 até 01/2018 e
07/2018 até 12/2018) e de Negócios (02/2018 até 06/2018).

# `r fontawesome::fa(name="people-carry")` Voluntariado

### Ordem DeMolay

* Membro Ativo (2014 - 2020) e Membro Sênior (2020 - Atualmente)
* Atuei como Ilustre Comendador Cavaleiro;
(08/2018 até 12/2018) e Mestre Conselheiro (01/2020 até 07/2020).

# `r fontawesome::fa(name="smile-beam")` Hobbies

### `r fontawesome::fa(name="book")` Leitura

* Amo ler qualquer tipo de coisa, desde que a escrita seja cativante e bem feita, me prendendo do começo ao fim;
* **Livros Favoritos:** "Estação Carandiru" (Dráuzio Varella), "Estarão as prisões obsoletas?" (Angela Davis), "O Hobbit" (J.R.R. Tolkien), "Battle Royale" (Koushun Takami).

### `r fontawesome::fa(name="gamepad")` Jogos

* Sou apaixonado por jogos desde muito pequeno. Meu gosto tende pra RPGs, jogos de aventura, metroidvanias e correlatos;
* **Jogos Favoritos:** Bravely Default, Metroid Dread, Pokémon Black, The Legend of Zelda: Breath of the Wild, Stardew Valley e Skyrim.

### `r fontawesome::fa(name="dice-d20")` RPGs de Mesa

* Ainda que este hobby esteja meio largado, gosto muito de RPGs de Mesa (sendo mestre ou jogador);
* **Sistemas Favoritos:** D&D 5e, Terra Devastada, Tiny Dungeon e (futuramente) Avatar Legends.

### `r fontawesome::fa(name="music")` Música

* Como 99,99% da população mundial, escuto música de vez em quando, e adoro fazer isso enquanto relaxo, faço tarefas domésticas ou estudo (aceito indicações, inclusive!);
* **Gêneros Musicais Favoritos:** Power/Thrash/Death Metal, City Pop, Vaporwave, Sertanejo e Trilhas Sonoras.
